server:
  port: 10900
spring:
  application:
    name: api-gateway
eureka:
  client:
    service-url:
      defaultZone: http://user:123@localhost:1111/eureka/
  instance:
    prefer-ip-address: true
zuul:
  routes:
    provider-user1: /pro/** #给制定的服务做映射 当前给provider-user1 添加映射为abc
  ignored-services: