server:
  port: 8097
spring:
  application:
    name: admin-security
  thymeleaf:
#    mode: HTML5
    mode: LEGACYHTML5
    cache: false
    check-template-location: true
    encoding: utf-8
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
    content-type: text/html
  resources:
    static-locations: classpath:/templates/,classpath:/static/
