server:
  port: 7901
spring:
  application:
    name: provider-user1
eureka:
  client:
    service-url:
      #defaultZone: http://user:123@eureka1:8761/eureka/
      defaultZone: http://user:123@localhost:1111/eureka/
  instance:
    prefer-ip-address: true